"""Shared constants for the Regicide action space."""

MAX_HAND_SIZE = 8
ATTACK_ACTION_COUNT = 286
DEFENSE_ACTION_COUNT = 1 << MAX_HAND_SIZE
DEFENSE_ACTION_OFFSET = ATTACK_ACTION_COUNT
SOLO_JESTER_ACTION_ID = ATTACK_ACTION_COUNT + DEFENSE_ACTION_COUNT
GLOBAL_ACTION_SPACE_SIZE = SOLO_JESTER_ACTION_ID + 1
